import React from "react";

export const metadata = {
    title: 'Create Next aa',
    description: 'Generated by create next d',
}

export default function RootLayout({children}: { children: React.ReactNode}) {

    return(
        <html lang="en">
            <body>
                {children}
            </body>
        </html>
    )
}